#!/bin/sh

check_char='\xE2\x9C\x93'
cross_char='\xE2\x9D\x8C'
green='\033[0;32m'
red='\033[031m'
nc='\033[0m'
check="$green$check_char$nc"
error="$red$cross_char$nc"


echo -e -n "Checking formatting code...\n"
cargo fmt --all -- --check
if [[ $? -ne 0 ]]; then
    echo -e -n "$error Bad format\n"
    exit 1
else
    echo -e -n "$check Nice format\n"
fi

echo -e -n "Checking code...\n"
cargo clippy -- -D warnings
if [[ $? -ne 0 ]]; then
    echo -e -n "$error Bad code\n"
    exit 1
else
    echo -e -n "$check Nice code\n"
fi

echo -e -n "Running tests... \n"
cargo test --color always
if [[ $? -ne 0 ]]; then
    echo -e -n "$error Test failed\n"
    exit 1
else
    echo -e -n "$check Nice tests\n"
fi
